# A sample Gemfile
source "https://rubygems.org"

gem "rake-pipeline", "~> 0.6.0", :git => "git://github.com/livingsocial/rake-pipeline.git"
gem "rake-pipeline-web-filters", "~> 0.6.0", :git => "git://github.com/wycats/rake-pipeline-web-filters.git"

gem "rack"
gem "rails"
